// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TextUserRepository is an autogenerated mock type for the TextUserRepository type
type TextUserRepository struct {
	mock.Mock
}

// CreateUserDetails provides a mock function with given fields: name, email, password
func (_m *TextUserRepository) CreateUserDetails(name string, email string, password string) {
	_m.Called(name, email, password)
}

// DeleteUser provides a mock function with given fields: user_id
func (_m *TextUserRepository) DeleteUser(user_id int) {
	_m.Called(user_id)
}

// ReadAllUsers provides a mock function with given fields:
func (_m *TextUserRepository) ReadAllUsers() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadAllUsers")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// UpdateUserDetails provides a mock function with given fields: user_id, name, email, password
func (_m *TextUserRepository) UpdateUserDetails(user_id int, name string, email string, password string) {
	_m.Called(user_id, name, email, password)
}

// NewTextUserRepository creates a new instance of TextUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTextUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TextUserRepository {
	mock := &TextUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
