// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TextBookRepository is an autogenerated mock type for the TextBookRepository type
type TextBookRepository struct {
	mock.Mock
}

// CreateBook provides a mock function with given fields: book_info
func (_m *TextBookRepository) CreateBook(book_info string) {
	_m.Called(book_info)
}

// CreateBookWithDetails provides a mock function with given fields: title, author, publish_year, isbn
func (_m *TextBookRepository) CreateBookWithDetails(title string, author string, publish_year string, isbn string) {
	_m.Called(title, author, publish_year, isbn)
}

// DeleteBook provides a mock function with given fields: book_id
func (_m *TextBookRepository) DeleteBook(book_id int) {
	_m.Called(book_id)
}

// ReadAllBooks provides a mock function with given fields:
func (_m *TextBookRepository) ReadAllBooks() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadAllBooks")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// UpdateBookWithDetails provides a mock function with given fields: book_id, title, author, publish_year, isbn
func (_m *TextBookRepository) UpdateBookWithDetails(book_id int, title string, author string, publish_year string, isbn string) {
	_m.Called(book_id, title, author, publish_year, isbn)
}

// NewTextBookRepository creates a new instance of TextBookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTextBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TextBookRepository {
	mock := &TextBookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
